### ISSUE TITLE
module "org.kde.plasma.core" is not installed.

### ISSUE THREAD

**Issue by mickdec** [3ximus/aerial-sddm-theme#11]
OS : Debian
I have installed :
     -sddm / QT (qml-module-multimedia, qtmultimedia5-dev)
     -gstreamer1.0-libav
     -phonon-backend-gstreamer-common
     -gstreamer1.0-plugins-good
I renamed QTMultimedia version 5.8 to 5.7 in Main.qml

And when i test the theme i get the error that "wallpapperFader is unavailable" and "org.kde.plasma.private.sessions" is not installed.

The same method have worked for my OS with KDE PLASMA.

**Comment by mickdec** [comment]
Removing WallpapperFader from Main.qml resolved my problem.

![image](https://user-images.githubusercontent.com/33021266/49878002-efc9eb00-fe26-11e8-887b-43d1e2283b27.png)

**Comment by 3ximus** [comment]
I was using some plasma dependencies on the WallpaperFader, I can do without them so I removed them
Let me know if it works for you

**Comment by 3ximus** [comment]
Did it work? Can i close the issue?

**Comment by mickdec** [comment]
Yes it is :)
