### ISSUE TITLE
Set focus on the password input on click

### ISSUE THREAD

**Issue by BobbyWibowo** [3ximus/aerial-sddm-theme#13]
At the moment, when I click on anywhere initially with a mouse, it blurs the background and shows the login form, but none of the inputs will gain focus. So I will have to manually set focus on the password input by clicking on it, before being able to type in my password.

If I choose to press a letter on the keyboard instead of clicking with a mouse initially, it also blurs the background and shows the login form, but the password input will gain focus.
However, the first character I type in (the one that triggers the login form to appear in the first place) will be *lost*. I'm guessing since there is no input initially.

So, unlike SDDM's Breeze theme, I can't just type in my password immediately once the greeter appears (since password input gains focus immediately on that theme).

At the very least it'd be great to have the initial mouse click also set focus on the password input, since typing a random letter from the keyboard to do so feels a bit off to me.

**Comment by BobbyWibowo** [comment]
> ..., since typing a random letter from the keyboard to do so feels a bit off to me.

For now I choose to dedicate Enter button for this instead. Feels alright to me.

The part about having initial mouse click set focus on the password input would still be great to have, however.

**Comment by 3ximus** [comment]
Hi. I added that on purpose because I'm used to tap the spacebar before the password. But I can add an option to type right away. And I will make the mouse click set focus on password input when I find the time for it :)
