### ISSUE TITLE
console user starting sddm.service cant preview video file

### ISSUE THREAD

**Issue by Schroedingersdoraemon** [3ximus/aerial-sddm-theme#22]
Hi 3ximus, when I start a xession by `startx` and use `sddm-greeter --test-mode --theme aerial`, the video file works fine and correctly as below.

![2020-05-09-154722_1920x1080_scrot](https://user-images.githubusercontent.com/43810289/81467623-7c3f2f80-920c-11ea-90a9-5b4b73aa2d69.png)

But if I enable sddm.service and restart the machine, it just became the picture in directory: background.jpg

My /usr/share/sddm/scripts/Xsetup is below
`xrandr --setprovideroutputsource modsetting NVIDIA-0`
`xrandr --auto`

I think the reason might be something about "systemctl enabled service" to support video but I can't found any relative answers

Appreciated if you can help

**Comment by 3ximus** [comment]
If it works in the preview it should work as a service, could the problem be the path to the videos? Did you download the videos or is it a url?

**Comment by Schroedingersdoraemon** [comment]
Hi 3ximus, so sorry to reply after such a long time.

These days I've actually tried a lot to fix this but eventually failed. So I decided to retern to simple `startx` to my dwm.
But I'll still try when my code ability improve in the future

Thanks a lot.
Yours.

**Comment by 3ximus** [comment]
I would start by checking the sddm logs to see if there is something there that might point you in the right direction
