### ISSUE TITLE
[FEATURE REQUEST] Download and cache videos after streaming

### ISSUE THREAD

**Issue by wakatara** [3ximus/aerial-sddm-theme#23]
In the linux xscreensaver version of Aerial, the videos are cached. 

It would be great if instead of always streaming the videos saved/cached 
(and if there was a way to configure which videos you wanted to use rather than random selections, that would be amazing too as kinda loving the underwater ones on my mac. Really would love them here.).

**Comment by 3ximus** [comment]
I don't see a point in caching the videos. There is only a fixed amount of links, if you want you can download them and create a playlist file like i describe here https://github.com/3ximus/aerial-sddm-theme#other-notes which allows you to choose which videos you want to play (although every time you login it will be a random pick between them)
