### ISSUE TITLE
[Feature Request] Hardware Acceleration / VA-API Support

### ISSUE THREAD

**Issue by tazihad** [3ximus/aerial-sddm-theme#24]
Since using CPU for the streaming makes the laptop hot. Is there any way you could use VA-API/Hardware Acceleration?

**Comment by 3ximus** [comment]
This is a simple theme written in QML, it cannot define what backend is used to decode the video. You'll have to set it up yourself. However if you are running gstreamer it should already support that...

I'll close the issue since its not a problem related to this theme
