### ISSUE TITLE
Installation of dependencies using apt

### ISSUE THREAD

**Issue by StefanLobbenmeier** [3ximus/aerial-sddm-theme#25]
Hi - I would like to add the installation steps required for debian like systems (i am on pop-os on this machine)

I should be able to find the packages on my own - will do a pull request with the steps I took to close this issue.

For now, I will document my steps here if that is ok with you.

**Comment by StefanLobbenmeier** [comment]
Found packages (WIP):

`sudo apt install gstreamer1.0-libav phonon-backend-gstreamer-common gstreamer1.0-plugins-good qml-module-qtquick-controls qt5-default `

**Comment by 3ximus** [comment]
Hi there, yes thank you, when you manage to find them all could you submit a pull request and add it to the README pls.
Thank you!
Cheers

**Comment by StefanLobbenmeier** [comment]
I need a hint regarding debugging this:

```

➜  aerial-sddm-theme git:(master) QML_IMPORT_TRACE=1 qml --verbose Main.qml

(lots of imports)
QQmlImports(file:///home/stefan/Downloads/aerial-sddm-theme/Main.qml)::resolveType: "MediaPlayer" => "QDeclarativeAudio" TYPE
[1]    44818 segmentation fault (core dumped)  QML_IMPORT_TRACE=1 qml --verbose Main.qml
➜  aerial-sddm-theme git:(master) 

```

Is there any command I can run to get more output that this

**Comment by StefanLobbenmeier** [comment]
Ok checking my installed packages now:

Arch Packages:
  - https://archlinux.pkgs.org/rolling/archlinux-extra-x86_64/gst-libav-1.18.4-1-aarch64.pkg.tar.xz.html
- https://archlinux.pkgs.org/rolling/archlinux-extra-x86_64/phonon-qt5-gstreamer-4.10.0-2-x86_64.pkg.tar.zst.html
- https://archlinux.pkgs.org/rolling/archlinux-extra-x86_64/gst-plugins-good-1.18.4-2-x86_64.pkg.tar.zst.html
- https://archlinux.pkgs.org/rolling/archlinux-extra-x86_64/qt5-quickcontrols-5.15.2-1-x86_64.pkg.tar.zst.html
- https://archlinux.pkgs.org/rolling/archlinux-extra-x86_64/qt5-graphicaleffects-5.15.2-1-x86_64.pkg.tar.zst.html
- https://archlinux.pkgs.org/rolling/archlinux-extra-x86_64/qt5-multimedia-5.15.2-1-x86_64.pkg.tar.zst.html


| Package Name         | Installation path                     | Ubuntu Package     | Installation Path                                      |
|----------------------|---------------------------------------|--------------------|--------------------------------------------------------|
| gst-libav            | /usr/lib/gstreamer-1.0/libgstlibav.so | gstreamer1.0-libav | /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so |
| phonon-qt5-gstreamer | /usr/lib/qt/plugins/phonon4qt5_backend/phonon_gstreamer.so | phonon-backend-gstreamer-common |                                                         only /usr/share/doc and /usr/share/icons/ ??? |
| gst-plugins-good     | /usr/lib/gstreamer-1.0/libgst* | gstreamer1.0-plugins-good | /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgst* |
| qt5-quickcontrols    |  /usr/lib/qt/qml/QtQuick/Controls/*  | qml-module-qtquick-controls | /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/* |
| qt5-graphicaleffects | /usr/lib/qt/qml/QtGraphicalEffects/*  | qml-module-qtgraphicaleffects | /usr/lib/x86_64-linux-gnu/qt5/qml/QtGraphicalEffects/* |
| qt5-multimedia       | /usr/include/qt/QtMultimedia/* | qml-module-qtmultimedia | /usr/lib/x86_64-linux-gnu/qt5/qml/QtMultimedia/* |

**Comment by StefanLobbenmeier** [comment]
From that table it looks like the gstreamer-common was a dud, phonon4qt5-backend-gstreamer might be the right module

Table after this change:
| Package Name         | Installation path                     | Ubuntu Package     | Installation Path                                      |
|----------------------|---------------------------------------|--------------------|--------------------------------------------------------|
| gst-libav            | /usr/lib/gstreamer-1.0/libgstlibav.so | gstreamer1.0-libav | /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgstlibav.so |
| phonon-qt5-gstreamer | /usr/lib/qt/plugins/phonon4qt5_backend/phonon_gstreamer.so | phonon4qt5-backend-gstreamer | /usr/lib/x86_64-linux-gnu/qt5/plugins/phonon4qt5_backend/phonon_gstreamer.so |
| gst-plugins-good     | /usr/lib/gstreamer-1.0/libgst* | gstreamer1.0-plugins-good | /usr/lib/x86_64-linux-gnu/gstreamer-1.0/libgst* |
| qt5-quickcontrols    |  /usr/lib/qt/qml/QtQuick/Controls/*  | qml-module-qtquick-controls | /usr/lib/x86_64-linux-gnu/qt5/qml/QtQuick/Controls/* |
| qt5-graphicaleffects | /usr/lib/qt/qml/QtGraphicalEffects/*  | qml-module-qtgraphicaleffects | /usr/lib/x86_64-linux-gnu/qt5/qml/QtGraphicalEffects/* |
| qt5-multimedia       | /usr/include/qt/QtMultimedia/* | qml-module-qtmultimedia | /usr/lib/x86_64-linux-gnu/qt5/qml/QtMultimedia/* |

**Comment by StefanLobbenmeier** [comment]
I also noticed that the qt5 multimedia on arch includes a lot more in its installation path, but I can not find another package like that for ubuntu.

And even after switching the phonon-qt5 package to the proper one the seg fault persists 

[1]    27556 segmentation fault (core dumped)  QML_IMPORT_TRACE=1 sddm-greeter --test-mode --theme .

**Comment by 3ximus** [comment]
I don't really know, could it be that you need some other gstreamer package ? how about `phonon-backend-gstreamer-common` ? Are you using Plasma as a desktop environment ? Because it probably has most of the packages that are necessary but I haven't listed them because I never installed this with another DE

**Comment by StefanLobbenmeier** [comment]
I am using 
kde-plasma-desktop/groovy,groovy,now 5:106ubuntu1 amd64 [installed]

as my desktop environment

`phonon-backend-gstreamer-common` is the one I tried first, but it looks like it only contains icons and documentation:

```
dpkg -L phonon-backend-gstreamer-common
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/phonon-backend-gstreamer-common
/usr/share/doc/phonon-backend-gstreamer-common/changelog.Debian.gz
/usr/share/doc/phonon-backend-gstreamer-common/copyright
/usr/share/icons
/usr/share/icons/hicolor
/usr/share/icons/hicolor/128x128
/usr/share/icons/hicolor/128x128/apps
/usr/share/icons/hicolor/128x128/apps/phonon-gstreamer.png
/usr/share/icons/hicolor/16x16
/usr/share/icons/hicolor/16x16/apps
/usr/share/icons/hicolor/16x16/apps/phonon-gstreamer.png
/usr/share/icons/hicolor/22x22
/usr/share/icons/hicolor/22x22/apps
/usr/share/icons/hicolor/22x22/apps/phonon-gstreamer.png
/usr/share/icons/hicolor/48x48
/usr/share/icons/hicolor/48x48/apps
/usr/share/icons/hicolor/48x48/apps/phonon-gstreamer.png
/usr/share/icons/hicolor/64x64
/usr/share/icons/hicolor/64x64/apps
/usr/share/icons/hicolor/64x64/apps/phonon-gstreamer.png
/usr/share/icons/hicolor/scalable
/usr/share/icons/hicolor/scalable/apps
/usr/share/icons/hicolor/scalable/apps/phonon-gstreamer.svg
```

Is there any command I can use to get a proper stacktrace instead of just this message with segmentation fault?

**Comment by 3ximus** [comment]
I see... 
You can try `strace` or  you can always use `gdb` or some other debugger

**Comment by StefanLobbenmeier** [comment]
Hmm strace tells me

```
openat(AT_FDCWD, "/etc/igfx_user_feature.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/igfx_user_feature.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
getpid()                                = 27745
openat(AT_FDCWD, "/etc/igfx_user_feature.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/igfx_user_feature.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
ioctl(22, DRM_IOCTL_I915_GEM_MADVISE, 0x7ffe9ab40ca0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe9ab40d00) = 0
ioctl(22, DRM_IOCTL_I915_GEM_MADVISE, 0x7ffe9ab40ca0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe9ab40d00) = 0
ioctl(22, DRM_IOCTL_I915_GEM_MADVISE, 0x7ffe9ab409d0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_MADVISE, 0x7ffe9ab40a80) = 0
ioctl(22, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe9ab40bf0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_MADVISE, 0x7ffe9ab409d0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe9ab40cc0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe9ab40cc0) = 0
ioctl(22, DRM_IOCTL_I915_GEM_CREATE, 0x7ffe9ab40c40) = 0
ioctl(22, DRM_IOCTL_I915_GEM_MADVISE, 0x7ffe9ab40c40) = 0
ioctl(22, DRM_IOCTL_I915_GEM_CREATE, 0x7ffe9ab40c30) = 0
ioctl(22, DRM_IOCTL_I915_GEM_SET_DOMAIN, 0x7ffe9ab40db0) = 0
openat(AT_FDCWD, "/etc/igfx_user_feature.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/igfx_user_feature.txt", O_RDONLY) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
[1]    27742 segmentation fault (core dumped)  strace sddm-greeter --test-mode --theme .
```

I was wondering whether maybe my gstreamer is bad so I also installed Kaffeine (which is supposed to use gstreamer), but that one is able to play the videos.

Anyway I guess I should take this issue to the qt developers instead?

**Comment by 3ximus** [comment]
I'm not sure, did you check all Kaffeine dependencies ? On their github they have 
```
apt-get install kdelibs5-dev libvlc-dev libxss-dev vlc \
	   libkf5coreaddons-dev libkf5i18n-dev libqt5x11extras5-dev \
	   libkf5windowsystem-dev \
	   libkf5solid-dev libkf5widgetsaddons-dev kio-dev \
	   qt5-default libdvbv5-dev \
	   cmake extra-cmake-modules make g++ gettext
```
Could one of these `lib` be what you need instead ?

**Comment by StefanLobbenmeier** [comment]
I installed everything from that list except
```
E: Package 'kdelibs5-dev' has no installation candidate
E: Package 'kio-dev' has no installation candidate
```
and the issue still appears.

But since Kaffeine is able to play videos I dont think that is the right direction. Anyway I think I will close this issue for now since it is not the fault of this theme and hope to get some support by the QT team.

**Comment by 3ximus** [comment]
ok good luck :+1: 
cheers

**Comment by StefanLobbenmeier** [comment]
I have some good news after all :) 

I guessed that my pop os with kde-plasma-desktop was a bit too complicated for a start, so I just tried it with Kubuntu instead.

Before installing the requirements I get an error message such as

```
[22:18:20.676] (WW) GREETER: GStreamer; Unable to play - "http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/b6-4.mov"
[22:18:20.728] (WW) GREETER: Warning: "No decoder available for type 'video/x-h264, stream-format=(string)avc, alignment=(string)au, level=(string)4, profile=(string)high, codec_data=(buffer)01640028ffe1001b27640028ac52140780227e5ffc00040005a808080db615af7be02001000528f90809cb, width=(int)1920, height=(int)1080, framerate=(fraction)30/1, pixel-aspect-ratio=(fraction)1/1, colorimetry=(string)bt709'."
```

Which I like a lot more than a random segfault :P 


After installing the dependencies (only gstreamer1.0-libav was missing) the preview worked with videos.

**Comment by 3ximus** [comment]
Perfect !! Thanks for this :+1: 
Cheers !
