### ISSUE TITLE
background image by day and night

### ISSUE THREAD

**Issue by hat3ph** [3ximus/aerial-sddm-theme#28]
I have modify the Main.qml to enable day and night background image rotation. Maybe you can implement it on the source.

https://github.com/hat3ph/aerial-sddm-theme/commit/bf8d0109254ae94fd64cb3154152fd9be1abeaf2
https://github.com/3ximus/aerial-sddm-theme/commit/93208ed813dce9ed55be77b1505b7cccf8eb04b9
https://github.com/3ximus/aerial-sddm-theme/commit/45a7f50599bf031813412304c71c79e76890552f

Thanks for the wonderful sddm theme.

**Comment by 3ximus** [comment]
Thank you, I replied in the pull request
