### ISSUE TITLE
[Feature Request] Please add in Undersea and other newer aerial videos

### ISSUE THREAD

**Issue by wakatara** [3ximus/aerial-sddm-theme#35]
I went over your list, and I *think* there are some videos that may be missing (in particular, all my fave undersea ones like 

I went looking for my personal fave from the Undersea theme and did not think I could see it in your "All" category.

I have yet to find a canonical list, but would be happy to help update the m3u's and provide a PR for you if you need a bit of help (also, if my Apple TV is any indication there seem to be some recent ones they just updated last week with the new Apple event... I think.. ). 

Spreadsheet here: 
https://docs.google.com/spreadsheets/d/1bboTohF06r-fafrImTExAPqM9m6h2m2lgJyAkQuYVJI/edit#gid=1684411812

**Comment by 3ximus** [comment]
Thanks for letting me know, I've added them to the All playlist
Cheers :+1:
