### ISSUE TITLE
only one password box config?

### ISSUE THREAD

**Issue by lidaling** [3ximus/aerial-sddm-theme#38]
How to hide username input box,just left the password one?

**Comment by 3ximus** [comment]
I think you need to remove this section here https://github.com/3ximus/aerial-sddm-theme/blob/06beb74994935743e0fae9413160d3ee936d4bf2/Main.qml#L210-L268
And delete any references to the `username_input_box` on the file

**Comment by 3ximus** [comment]
No follow up ...
