### ISSUE TITLE
Lubuntu 22.04 require libqt5multimedia5-plugins

### ISSUE THREAD

**Issue by hat3ph** [3ximus/aerial-sddm-theme#39]
Running aerial-sddm-theme on Lubuntu 22.04 with LXQt, it require libqt5multimedia5-plugins package.
I just need below 3 additional package to make it work out of the box.

sudo apt-get install gstreamer1.0-libav qml-module-qtmultimedia libqt5multimedia5-plugins

**Comment by 3ximus** [comment]
Thank you, can you make a pull request and update the readme please ?

**Comment by hat3ph** [comment]
Done

https://github.com/3ximus/aerial-sddm-theme/pull/40
