### ISSUE TITLE
Cant download the videos for offline usage

### ISSUE THREAD

**Issue by cranky-pythonista** [3ximus/aerial-sddm-theme#42]
Im trying to download the videos for offline usage via the procedure(https://github.com/3ximus/aerial-sddm-theme#other-notes) given but its not working. Im on vanilla arch. Please guide.

**Comment by 3ximus** [comment]
What doesn't work exactly? Be more specific with your problem

**Comment by cranky-pythonista** [comment]
> What doesn't work exactly? Be more specific with your problem

My bad,, what I meant was I dont know what exactly to do. Where to put the given commands and how to proceed. Very new to this.

**Comment by 3ximus** [comment]
Run the commands on your shell
