### ISSUE TITLE
[Feature Request] 12 hour clock format

### ISSUE THREAD

**Issue by MonstrousOgre** [3ximus/aerial-sddm-theme#47]
The time is currently shown in 24 hour format. I'd love the option to have it in a 12 hour format.

**Comment by 3ximus** [comment]
Sorry, but this is not something I feel like implementing right now...
You can either configure the default clock component on your own (see this thread
https://askubuntu.com/a/784181/541661) or you can implement a custom clock component on this theme and submit a pull request. Here's how it was done somewhere else:
https://github.com/MarianArlt/sddm-sugar-dark/blob/master/Components/Clock.qml
Cheers!
