### ISSUE TITLE
Incompatible with v0.21.0 of SDDM

### ISSUE THREAD

**Issue by Chr1s70ph** [3ximus/aerial-sddm-theme#49]
In their latest update to version [0.21.0](https://github.com/sddm/sddm/releases/tag/v0.21.0) they added QT-6 Support.
This breaks the theme and makes it unusable sadly.

<details open>
<summary>Output of sddm when running the greeter with the theme</summary>
<br>
<pre><code>High-DPI autoscaling not Enabled
Reading from "/usr/share/wayland-sessions/hyprland.desktop"
Reading from "/usr/share/wayland-sessions/sway-nvidia.desktop"
Reading from "/usr/share/wayland-sessions/sway.desktop"
Reading from "/usr/share/xsessions/i3-with-shmlog.desktop"
Reading from "/usr/share/xsessions/i3.desktop"
Loading theme configuration from "/usr/share/sddm/themes/aerial/theme.conf"
Socket error:  "QLocalSocket::connectToServer: Invalid name"
Loading file:///usr/share/sddm/themes/aerial/Main.qml...
file:///usr/share/sddm/themes/aerial/Main.qml:63:19: Playlist is not a type 
             playlist: Playlist { 
                       ^
file:///usr/share/sddm/themes/aerial/Main.qml:63:19: Playlist is not a type 
             playlist: Playlist { 
                       ^
Fallback to embedded theme
file:///usr/lib/qt6/qml/SddmComponents/LayoutBox.qml:35:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/qt6/qml/SddmComponents/ComboBox.qml:105:9: QML Image: Cannot open: file:///usr/lib/qt6/qml/SddmComponents/angle-down.png
file:///usr/lib/qt6/qml/SddmComponents/ComboBox.qml:105:9: QML Image: Cannot open: file:///usr/lib/qt6/qml/SddmComponents/angle-down.png
qrc:/theme/Main.qml:41:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Adding view for "DP-0" QRect(0,1440 5120x1440)
Loading file:///usr/share/sddm/themes/aerial/Main.qml...
file:///usr/share/sddm/themes/aerial/Main.qml:63:19: Playlist is not a type 
             playlist: Playlist { 
                       ^
file:///usr/share/sddm/themes/aerial/Main.qml:63:19: Playlist is not a type 
             playlist: Playlist { 
                       ^
Fallback to embedded theme
file:///usr/lib/qt6/qml/SddmComponents/LayoutBox.qml:35:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
file:///usr/lib/qt6/qml/SddmComponents/ComboBox.qml:105:9: QML Image: Cannot open: file:///usr/lib/qt6/qml/SddmComponents/angle-down.png
file:///usr/lib/qt6/qml/SddmComponents/ComboBox.qml:105:9: QML Image: Cannot open: file:///usr/lib/qt6/qml/SddmComponents/angle-down.png
qrc:/theme/Main.qml:41:5: QML Connections: Implicitly defined onFoo properties in Connections are deprecated. Use this syntax instead: function onFoo(<arguments>) { ... }
Adding view for "DP-2" QRect(840,0 3440x1440)
qt.qml.context: file:///usr/lib/qt6/qml/SddmComponents/PictureBox.qml:106:13 Parameter "event" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead.
qt.qml.context: file:///usr/lib/qt6/qml/SddmComponents/PictureBox.qml:106:13 Parameter "event" is not declared. Injection of parameters into signal handlers is deprecated. Use JavaScript functions with formal parameters instead.
</code></pre>
</details>

**Comment by Chr1s70ph** [comment]
As it turns out, it is compatible. I did some testing with the greeters in test mode, and those don't seem to work.

**Comment by 3ximus** [comment]
Greate news :D 
Thanks
