### ISSUE TITLE
Video works on test, but not on startup

### ISSUE THREAD

**Issue by djpalumbo** [3ximus/aerial-sddm-theme#5]
When I run the theme in a terminal, the videos run just fine (after briefly seeing the default background image).

But on startup, I'm seeing a wall of the same error, _Error: "Could not resolve server name."_ Now, it occurred to me that it might've been an issue with the timing of the NetworkManager service, which I tried to compensate for by using the NetworkManager-wait-online.service, but that didn't seem to do anything to fix the issue.

I've already tried reinstalling all the dependencies. Any ideas?

**Comment by 3ximus** [comment]
The most obvious problem would be that the network manager is not connecting before you log in. If that is the problem changing the wait-online service won't make a diference.
You should try to configure the network manager to allow any user to connect to the network. If you are on a wifi connection you might need to store the wifi password for all users aswell (it will not be encrypted however).

**Comment by djpalumbo** [comment]
Thanks for the reply. Allowing the connection for all users did the trick.

For anyone else with this problem, all I had to do was this:
- Open the 'Edit connections' menu for NetworkManager (I'm using nm-applet)
- Select a network and edit it
- Go to the 'General' tab and check the box for 'All users may connect to this network'

After that, it worked! I very much appreciate the help.

**Comment by 3ximus** [comment]
Glad it worked out. Cheers

**Comment by imjasonmiller** [comment]
I ran into a similar issue, where it worked in `--test-mode`, but not on startup.

In my case, the videos were supposed to load from disk. They didn't, because they could not be accessed in the directory I had them in. I ended up solving it by moving the videos to a directory that is accessible, the `aerial-sddm-theme` directory itself that is.
