### ISSUE TITLE
*Feature request - Set the hour as 12hr (AM - PM)

### ISSUE THREAD

**Issue by los95** [3ximus/aerial-sddm-theme#51]
Hello, I noticed that you don't really use this anymore but do you have any clue on how one can change the clock from 24 hour to 12 AM/PM? I have tried to change the qml around but can't make it work.

**Comment by 3ximus** [comment]
I've described how to set that up on the README of the repo. I've made a configuration file where you can configure that

https://github.com/3ximus/aerial-sddm-theme?tab=readme-ov-file#changing-settings-in-themeconfuser

**Comment by los95** [comment]
I apologize but I have read the README and there doesn't seem to have a description to change the clock format unless it is the day_time_start and day_time_end. Those would be just for the playlist of the videos, however. I have read that changing the locale can help but other themes can do it without the need for that change.

**Comment by 3ximus** [comment]
Oh my bad, I didn't read your question properly. I guess we can just replace the builtin clock by a custom component. I've pushed a commit that does that and allows you to configure the timeFormat in the `theme.config` file. You can use this line:
```ini
timeFormat="h:m ap"
```
to achieve what you want. Other formats are described here:
https://doc.qt.io/qt-5/qml-qtqml-qt.html#formatDateTime-method

**Comment by los95** [comment]
Yes, that's it. Thanks! I managed to get another solution by grabbing a clock component from another theme and reworked it in the main.qml. I also have implemented a virtual keyboard just to have it. Might just fork this with that stuff added.
