### ISSUE TITLE
Error when running in test mode: MediaPlayer is not a type

### ISSUE THREAD

**Issue by analgaming12** [3ximus/aerial-sddm-theme#52]
I'm running it in test mode and get this error:
```
The current theme cannot be loaded due to the errors below, please select another theme

file://home/(removed)/Downloads/aerial-sddm-theme-master/Main.qml:157:5:MediaPlayer is not a type
```
I've downloaded all dependencies listed and also downloaded qt6-multimedia(both gstreamer and ffmpeg) to no avail. Any help would be appreciated.

**Comment by hat3ph** [comment]
Using what distro?

**Comment by analgaming12** [comment]
Arch linux

**Comment by 0x454d505459** [comment]
Got the same issue when using the test command, using `sddm-greeter --test-mode --theme /usr/share/sddm/themes/aerial-sddm-theme/` works fine but when running `sddm-greeter-qt6` it break line 70 with `VideoOutput is not a type`

**Comment by hat3ph** [comment]
> Got the same issue when using the test command, using `sddm-greeter --test-mode --theme /usr/share/sddm/themes/aerial-sddm-theme/` works fine but when running `sddm-greeter-qt6` it break line 70 with `VideoOutput is not a type`

Did you install qt6 component qt6-quickcontrols qt6-graphicaleffects qt6-multimedia?

**Comment by hat3ph** [comment]
> If you have only qt-5 multimedia installed (and not qt6-multimedia) the issue persists ?

I have an test arch linux vm with fresh sddm installed, with qt6-multimedia installed, sddm-greeter-qt6 not working with error "Playlist is not a type."

I think is because Qt6 QMediaPlayer no longer support playlist.

https://doc.qt.io/qt-6/qtmultimedia-changes-qt6.html

**Comment by 3ximus** [comment]
I see... Well unless someone wants to spend the time on this and make a PR I'll close the issue for now because I don't have any plans to working on this feature :/
