### ISSUE TITLE
An on-screen keyboard pops up during login and the font is different

### ISSUE THREAD

**Issue by AMonreale** [3ximus/aerial-sddm-theme#6]
Title.
I'm on Manjaro KDE, everything updated and all dependencies installed.

edit: nevermind the on-screen keyboard, it seems  a bug related with Manjaro. But the font is still different.

**Comment by 3ximus** [comment]
What font is being displayed, can you tell? Show me a screenshot. You can take one by previewing the theme with `sddm-greeter --theme <theme-directory>`
Also which font are you using in your `theme.conf.user`, or `theme.conf` if you dont have the other file

**Comment by AMonreale** [comment]
So, I checked both ```theme.conf``` and ```theme.conf.user``` and there were two different fonts, in the first file it was ```DejaVu Sans```, in the second ```Misc Fixed```.

Edited ```theme.conf.user``` with ```DejaVu Sans``` and now looks great! Thank you for the tip!

[Before](https://i.imgur.com/TEH5EEG.png) and [after](https://i.imgur.com/VdlHfBf.png).

**Comment by 3ximus** [comment]
Glad you got it working! You can change any of the settings I mentioned in the README in the file `theme.conf.user`, if you delete this file or remove any of the entries they will default to the ones in the `theme.conf` and will give the look of the first screenshots (as opposed to the last one which is given by the `theme.conf.user` that I supplied)
Cheers!

**Comment by AMonreale** [comment]
I wanted to post the solution about the virtual keyboard popping up during the login, just in case someone stumble upon this post.

Edit the ```/etc/sddm.conf``` file and add ```InputMethod=``` in the ```[General]``` section

**Comment by BobbyWibowo** [comment]
> I wanted to post the solution about the virtual keyboard popping up during the login, just in case someone stumble upon this post.
> 
> Edit the `/etc/sddm.conf` file and add `InputMethod=` in the `[General]` section

Thanks! I was also having the same issue on KDE neon 5.15 (`sddm-0.17.0-2+18.04+bionic+build15.amd64`, if it matters).
