### ISSUE TITLE
Theme not loading due to error in Main.qml

### ISSUE THREAD

**Issue by Linus045** [3ximus/aerial-sddm-theme#60]
`font.bold` is declared twice which causes an error on my system.
![image](https://github.com/user-attachments/assets/b0cf5986-a98e-4820-93e9-e1dc22d7c91b)

See file: https://github.com/3ximus/aerial-sddm-theme/blob/df65f8065aaf33cd0ad177878cb94ce08020e4a7/Main.qml#L266-L268

**Comment by 3ximus** [comment]
Thank you for reporting, must have been an issue on the latest pull request. I've fixed it. Cheers!
